package:
  name: pdb2pqr
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
  path: ../..

build:
  noarch: python
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}
  entry_points:
    - pdb2pqr30=pdb2pqr.main:main
    - dx2cube=pdb2pqr.main:dx_to_cube
    - psize=pdb2pqr.psize:main
    - inputgen=pdb2pqr.inputgen:main

requirements:
  host:
    - pip
    - python >= 3.6
  run:
    - python >=3.6
    - mmcif_pdbx >=1.1.2
    - numpy >=1.17
    - propka >=3.2
    - requests
    - docutils <0.18

about:
  home: https://github.com/acellera/pdb2pqr/
  license: "Custom"
  license_file: LICENSE.md
  summary: A molecule reading/writing and manipulation package.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - stefdoerr
